### PR TITLE
Fix import of @PactFolder

### PR DESCRIPTION
**Pull request by tinexw**
Not sure if this annotation is even relevant... But if you want to use it then the import is wrong and no pacts are found.

### CODE REVIEW

**Comment by bethesque** [comment]
Any idea why the test fails @tinexw?

**Comment by tinexw** [comment]
> Any idea why the test fails @tinexw?

tbh no. I assume it's something with the env variables not being replaced (at least locally I get a Runtime Exception in that case). But I was also not sure if this test was even supposed to be run as part of the travis job... since it has the `PactBroker` and `PactFolder` annotation both.

**Comment by tinexw** [comment]
Yep, it's the variable

`java.lang.RuntimeException: Could not resolve property "PACT_BROKER_TOKEN" in the system properties or environment variables and no default value is supplied`

**Comment by YOU54F** [comment]
Hi @tinexw , I have merged these changes now whilst converting over to GH actions.

Thanks for your contribution!

**Pull request merged**
